# Test configuration for integration tests
# Environment Variables Required:
# export POSTGRES_PASSWORD="password"

[metadata]
name = "outboxx-test"
version = "1.0"
environment = "test"

# Plugin registry - defines available source and sink types
[plugins]
sources = ["postgres"]
sinks = ["kafka"]
flows = ["direct"]

# Source configuration for tests
[source]
type = "postgres"

[source.postgres]
host = "localhost"
port = 5432
database = "outboxx_test"
user = "postgres"
password_env = "POSTGRES_PASSWORD"
slot_name = "outboxx_test_slot"
publication_name = "outboxx_publication"

# Sink configuration for tests
[sink]
type = "kafka"

[sink.kafka]
brokers = ["localhost:9092"]

# Test stream
[[streams]]
name = "test-stream"

[streams.source]
type = "postgres"
table = "users"
operations = ["INSERT", "UPDATE", "DELETE"]

[streams.flow]
type = "direct"
format = "json"
include_schema = true
include_timestamp = true

[streams.sink]
type = "kafka"
topic = "test.public.users"
partition_key = "id"

# Table filter for tests
[tables]
include = ["users", "products", "orders"]
exclude = ["system_logs"]