# ZiCDC Configuration Example
# This file shows all available configuration options

# PostgreSQL source configuration
source:
  host: "localhost"
  port: 5432
  database: "myapp"
  user: "postgres"
  password: "password"

  # Logical replication slot configuration
  slot_name: "zicdc_slot"
  publication_name: "zicdc_publication"

  # Connection settings
  connection_timeout_ms: 5000
  query_timeout_ms: 30000
  max_retries: 3

# Kafka target configuration
target:
  brokers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"

  # Topic configuration
  topic_prefix: "cdc"
  topic_suffix: ""

  # Producer settings
  batch_size: 1000
  flush_interval_ms: 100
  compression_type: "gzip"

  # Reliability settings
  acks: "all"
  retries: 2147483647
  max_in_flight_requests: 5

# Table filtering configuration
tables:
  # Include specific tables (empty means all tables)
  include:
    - "users"
    - "orders"
    - "products"
    - "inventory"

  # Exclude specific tables
  exclude:
    - "audit_logs"
    - "temp_*"

  # Column filtering
  exclude_columns:
    - "password_hash"
    - "internal_notes"
    - "created_by_system"

# Message formatting
format:
  type: "json"  # json, avro (future)

  # JSON-specific settings
  json:
    include_schema: true
    include_timestamp: true
    flatten_nested: false
    null_handling: "explicit"  # explicit, omit, empty_string

# Performance and resource settings
performance:
  # WAL processing
  wal_buffer_size: 1024  # KB
  max_wal_records_batch: 1000

  # Memory management
  max_memory_usage_mb: 100
  gc_interval_ms: 60000

# Monitoring and observability
monitoring:
  # Metrics endpoint
  metrics_enabled: true
  metrics_port: 8080
  metrics_path: "/metrics"

  # Health check
  health_check_enabled: true
  health_check_port: 8081
  health_check_path: "/health"

# Logging configuration
logging:
  level: "info"  # trace, debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file

  # File logging (when output is "file")
  file:
    path: "/var/log/zicdc/zicdc.log"
    max_size_mb: 100
    max_files: 5
    rotate: true

# State management for crash recovery
state:
  # LSN tracking
  checkpoint_interval_ms: 5000
  state_file: "/var/lib/zicdc/state.json"
  backup_state_files: 3

  # Recovery settings
  recovery_timeout_ms: 30000
  skip_corrupted_records: false

# Development and debugging
development:
  # Debug mode
  debug_enabled: false
  debug_log_wal_records: false
  debug_log_kafka_messages: false

  # Testing
  dry_run: false
  max_records: 0  # 0 means unlimited